### ISSUE TITLE
Create diagrams presenting migration flow

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/migratio#8]

**Comment by pasuder** [comment]
![openstack2openstack](https://cloud.githubusercontent.com/assets/3436085/6143268/1640f924-b1c6-11e4-8b53-a2e542f38553.png)
@mkasztelnik do you like it?

**Comment by mkasztelnik** [comment]
Nice, can you additionally add information which bash scripts are executed in each step?

**Comment by mkasztelnik** [comment]
What is more please add these updated images into `README.md`

**Comment by pasuder** [comment]
Update versions of diagrams:

![openstack2openstack](https://cloud.githubusercontent.com/assets/3436085/6143497/09016a24-b1ca-11e4-9a44-543fa83488e2.png)

![openstack2amazon](https://cloud.githubusercontent.com/assets/3436085/6143521/73f4b3c2-b1ca-11e4-8bd3-4e5dbd85bed3.png)

**Comment by pasuder** [comment]
Added in #7

**Comment by mkasztelnik** [comment]
Good job :clap::clap::clap:
